// client-tmp/angular/src/app/layouts/blank/blank.layout.ts
import { Component, ElementRef, ViewChild, AfterViewInit } from '@angular/core';
import {
  applyMode,
  injectThemeStyles,
  resolveInitialMode,
} from '@genesislcap/rapid-design-system';
import { activeTheme } from '../../../styles/active-theme';

@Component({
  selector: 'app-blank-layout',
  templateUrl: './blank.layout.html',
  styleUrls: ['./blank.layout.css'],
})
export class BlankLayoutComponent implements AfterViewInit {
  @ViewChild('designSystemProvider') designSystemProviderElement!: ElementRef;

  ngAfterViewInit() {
    injectThemeStyles(this.designSystemProviderElement.nativeElement, activeTheme);
    applyMode(
      this.designSystemProviderElement.nativeElement,
      activeTheme,
      resolveInitialMode(activeTheme),
    );
  }
}

// client-tmp/react/src/layouts/blank/BlankLayout.tsx
import { applyMode, injectThemeStyles, resolveInitialMode } from '@genesislcap/rapid-design-system';
import React, { ReactNode, useEffect, useRef } from 'react';
import { activeTheme } from '../../styles/active-theme';
import styles from './BlankLayout.module.css';

interface BlankLayoutProps {
  children: ReactNode;
}

const BlankLayout: React.FC<BlankLayoutProps> = ({ children }) => {
  const designSystemProviderRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (designSystemProviderRef.current) {
      injectThemeStyles(designSystemProviderRef.current, activeTheme);
      applyMode(designSystemProviderRef.current, activeTheme, resolveInitialMode(activeTheme));
    }
  }, []);

  return (
    <rapid-design-system-provider ref={designSystemProviderRef} className={styles['blank-layout']}>
      <section className={styles.content}>{children}</section>
    </rapid-design-system-provider>
  );
};

export default BlankLayout;
