// client-tmp/react/src/share/foundation-login.ts
import { configure, defaultAuthConfig } from '@genesislcap/foundation-auth/config';
import { getUser } from '@genesislcap/foundation-user';
import { AUTH_PATH } from '@/config';
import { GENESIS_SOCKET_URL } from '@genesislcap/foundation-utils';
import { Connect } from '@genesislcap/foundation-comms';
import { DI } from '@genesislcap/web-core';
import type { NavigateFunction } from 'react-router';

/**
 * Configure the micro frontend
 */
export const configureFoundationLogin = ({navigate}: { navigate: NavigateFunction}) => {
  const baseElement = document.querySelector('base');
  const basePath = baseElement?.getAttribute('href') || '';
  const connect = DI.getOrCreateDOMContainer().get(Connect);


  configure({
    name: 'client-app-login',
    omitRoutes: ['request-account', 'forgot-password'],
    fields: {
      ...defaultAuthConfig.fields,
      username: {
        ...defaultAuthConfig.fields.username,
      },
    },
    hostPath: basePath + AUTH_PATH,
    postLoginRedirect: async () => {
      const url = GENESIS_SOCKET_URL;
      await connect.connect(url);

      // const lastPath = getUser().lastPath()?.replace(basePath, '') || '';
      const redirectUrl = '/{{kebabCase routes.[0].name}}';
      navigate(redirectUrl);
    },
  })
}

// client-tmp/angular/src/app/share/foundation-login.ts
import {configure, define} from '@genesislcap/foundation-login';
import type { Router } from '@angular/router';
import { AUTH_PATH } from '../app.config';
import { css } from '@microsoft/fast-element';
import { DI } from '@microsoft/fast-foundation';
import logo from '../../assets/logo.svg';

// eslint-disable-next-line
declare var ENABLE_SSO: boolean;

const ssoSettings =
  typeof ENABLE_SSO !== 'undefined' && ENABLE_SSO === true
    ? {
        autoAuth: true,
        sso: {
          toggled: true,
          identityProvidersPath: 'sso/list',
        },
      }
    : {};

/**
 * Configure the micro frontend
 */
export const configureFoundationLogin = ({
  router,
}: {
  router: Router;
}) => {
  configure(DI.getOrCreateDOMContainer(), {
    showConnectionIndicator: true,
    hostPath: AUTH_PATH,
    redirectHandler: () => {
      router.navigate(['{{kebabCase routes.[0].name}}'])
    },
    ...ssoSettings,
    logo: css `
      content: url("${logo}");
    `,
  });

  return define({
    name: `client-app-login`,
  });
}
