// client-tmp/react/src/App.tsx
import { useEffect, useState } from 'react';
import {Routes, Route, useLocation, BrowserRouter} from 'react-router';
import {
  setApiHost,
  getLayoutNameByRoute,
  {{#if FDC3.channels.length~}}
  listenToChannel,
  onFDC3Ready,
  {{/if}}
} from './utils';
import { customEventFactory, registerStylesTarget } from '@/pbc/utils';
import LayoutWrapper from './layouts/LayoutWrapper';
import LayoutName from '@/types/LayoutName';
import { AUTH_PATH, routeLayouts } from './config';
import { AuthProvider } from './store/AuthContext';
import { RoutesProvider, useRoutesContext } from './store/RoutesContext';
import AuthPage from './pages/AuthPage/AuthPage';
import { registerComponents as genesisRegisterComponents } from './share/genesis-components';
import ProtectedGuard from './guards/ProtectedGuard';
import { storeService } from '@/services/store.service';

const DynamicLayout = () => {
  const location = useLocation();
  const [layoutName, setLayoutName] = useState<LayoutName>(routeLayouts[location.pathname]  || 'default');
  const handleRouteChange = (location: any) => {
    setLayoutName(getLayoutNameByRoute(location.pathname));
  };
  const route = useRoutesContext().find((r) => r.path === location.pathname);
  let pageComponent;
  let content;

  useEffect(() => {
    handleRouteChange(location);

    return () => {
    }
  }, [location]);

  if (route) {
    pageComponent = route.element;
  } else {
    pageComponent = <AuthPage />;
  }

  if (location.pathname === `/${AUTH_PATH}` || location.pathname === '/') {
    content = pageComponent;
  } else {
    content = <ProtectedGuard>{pageComponent}</ProtectedGuard>
  }

  return <LayoutWrapper layout={layoutName}>{content}</LayoutWrapper>

};

interface AppProps {
  rootElement: HTMLElement;
}

const App: React.FC<AppProps> = ({ rootElement }) => {
  const [isStoreConnected, setIsStoreConnected] = useState(false);
  const dispatchCustomEvent = (type: string, detail?: any) => {
    rootElement.dispatchEvent(customEventFactory(type, detail));
  };
  const handleStoreConnected = (event: CustomEvent) => {
    storeService.onConnected(event);
  };
  {{#if FDC3.channels.length~}}
  const FDC3ReadyHandler = () => {
    {{#each FDC3.channels}}
    listenToChannel('{{this.name}}', '{{this.type}}', (result) => {
      console.log('Received FDC3 channel message on: {{this.name}} channel, type: {{this.type}}', result);
      // TODO: Add your listener logic here
      // E.g. open a modal or route to specific page: Route.path.push(`[Route name]`);
    });
    {{/each}}
  };
  {{/if}}

  setApiHost();
  genesisRegisterComponents();

  useEffect(() => {
    registerStylesTarget(document.body, 'main');
    {{#if FDC3.channels.length~}}
    onFDC3Ready(FDC3ReadyHandler);
    {{/if}}
    if (!isStoreConnected) {
      rootElement.addEventListener('store-connected', handleStoreConnected);
      dispatchCustomEvent('store-connected', rootElement);
      dispatchCustomEvent('store-ready', true);
      setIsStoreConnected(true);
    }

    return () => {
      if (isStoreConnected) {
        rootElement.removeEventListener('store-connected', handleStoreConnected);
        dispatchCustomEvent('store-disconnected');
      }
    };
  }, [isStoreConnected]);

  return (
    <AuthProvider>
      <RoutesProvider>
        <BrowserRouter>
          <Routes>
            <Route path="*" element={<DynamicLayout />} />
          </Routes>
        </BrowserRouter>
      </RoutesProvider>
    </AuthProvider>
  );
};

export default App;

// client-tmp/angular/src/app/app.component.ts
import { AfterViewInit, Component, ElementRef, OnDestroy, OnInit } from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';
import { Connect } from '@genesislcap/foundation-comms';
import getLayoutNameByRoute from './utils/getLayoutNameByRoute';
import type { LayoutComponentName } from './types/layout';
import { configureFoundationAuth } from './share/foundation-auth';
import { registerComponents } from './share/genesis-components';
import { getStore } from './store';
import { customEventFactory, registerStylesTarget } from '../pbc/utils';
{{#if FDC3.channels.length}}
import { listenToChannel, onFDC3Ready } from './utils';
{{/if}}

@Component({
  selector: '{{rootElement}}',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent implements OnInit, OnDestroy, AfterViewInit {
  layoutName?: LayoutComponentName;
  title = '{{capitalCase appName}}';
  store = getStore();

  // @ts-ignore
  @Connect connect: Connect;

  constructor(
    private el: ElementRef,
    router: Router,
  ) {
    // @ts-ignore
    configureFoundationAuth({ router, connectService: this.connect });
      
    // Set layout componet based on route
    router.events.subscribe((event: any) => {
      if (event instanceof NavigationEnd) {
        this.layoutName = getLayoutNameByRoute(event.urlAfterRedirects);
      }
    });
  }

  ngOnInit() {
    this.addEventListeners();
    this.readyStore();
    registerStylesTarget(this.el.nativeElement, 'main');
    this.loadRemotes();
  }

  ngOnDestroy() {
    this.removeEventListeners();
    this.disconnectStore();
  }

  async loadRemotes() {
    await registerComponents();
  }

  addEventListeners() {
    this.el.nativeElement.addEventListener('store-connected', this.store.onConnected);
  }

  removeEventListeners() {
    this.el.nativeElement.removeEventListener('store-connected', this.store.onConnected);
  }

  readyStore() {
    this.dispatchCustomEvent('store-connected', this.el.nativeElement);
    this.dispatchCustomEvent('store-ready', true);
  }

  disconnectStore() {
    this.dispatchCustomEvent('store-disconnected');
  }

  dispatchCustomEvent(type: string, detail?: any) {
    this.el.nativeElement.dispatchEvent(customEventFactory(type, detail));
  }

  ngAfterViewInit() {
    {{#if FDC3.channels.length}}
    onFDC3Ready(this.FDC3ReadyHandler);
    {{/if}}
  }

  {{#if FDC3.channels.length}}
  FDC3ReadyHandler = () => {
    {{#each FDC3.channels}}
    listenToChannel('{{this.name}}', '{{this.type}}', (result) => {
      console.log('Received FDC3 channel message on: {{this.name}} channel, type: {{this.type}}', result);
      // TODO: Add your listener logic here
      // E.g. open a modal or route to specific page: Route.path.push(`[Route name]`);
    });
    {{/each}}
  };
  {{/if}}
}

<zero-design-system-provider>
  <router-outlet />
</zero-design-system-provider>
