// client-tmp/angular/src/pbc/container.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, ElementRef, OnInit, ViewChild } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { deriveElementTag } from './utils';

/**
 * An app level container for the lazy loading of the web component based PBC routes in angular router.
 */
@Component({
    standalone: true,
    selector: 'pbc-container',
    template: `<div #container class="container"></div>`, // todo get rid of the extra div
    styles: [`
        .container {
            width: 100%;
            height: 100%;
        }
    `],
    schemas: [
        CUSTOM_ELEMENTS_SCHEMA
    ],
})
export class PBCContainer implements OnInit {
    @ViewChild('container', { static: true }) container!: ElementRef;

    constructor(private route: ActivatedRoute) {}

    async ngOnInit() {
        const { pbcElement, pbcElementTag } = this.route.snapshot.data ?? {};
        if (!pbcElement) {
            return;
        }
        /**
         * Account for PBC elements being a mix of constructors and lazy loading functions
         */
        const element = pbcElement.define ? pbcElement : await pbcElement();
        const tagName = pbcElementTag || deriveElementTag(element.name);
        const customElement = document.createElement(tagName);
        this.container.nativeElement.appendChild(customElement);
    }
}

// client-tmp/react/src/pbc/container.tsx
import React, { useEffect, useRef } from 'react';
import { deriveElementTag } from './utils';
import { useRoutesContext } from '@/store/RoutesContext';
import { useLocation } from 'react-router-dom';


const PBCContainer: React.FC = () => {
  const containerRef = useRef<HTMLDivElement>(null);
  const routes = useRoutesContext();
  const location = useLocation();

  useEffect(() => {
    const loadElement = async () => {
      const route = routes.find(({ path }) => path === location.pathname);
      const { data } = route || {};
      const { pbcElement, pbcElementTag } = data || {};

      if (!pbcElement) {
        return;
      }
      const element = pbcElement.define ? pbcElement : await pbcElement();
      const tagName = pbcElementTag || deriveElementTag(element.name);
      const customElement = document.createElement(tagName);
      if (containerRef.current) {
        containerRef.current.replaceChildren();
        containerRef.current.appendChild(customElement);
      }
    };

    loadElement();
  }, [location.pathname, routes]);

  return <div ref={containerRef} className="container" style={{ width: '100%', height: '100%' }}></div>;
};

export default PBCContainer;
